# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180129_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校')], default='pxjg', max_length=20),
        ),
    ]
