# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全国知名', max_length=4, verbose_name='机构标签'),
        ),
    ]
