# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180207_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后端开发', max_length=10, verbose_name='课程类别'),
        ),
    ]
